- ImageD11/indexing.py
First commit and pull request on github :-) .
I added more printing on the ring assignments as disscussed last time.
I Needed to "estimate" the measured data (omegra ranges) from gv file in order to compute the epected rings and peaks per ring.
Maybe it is better to just ask the user for the omega ranges!
> Updating the report on assignments and getting omage ranges from gv file

- .circleci/config.yml
- appveyor.yml
work in progress on #32 (hooks for circleci and appveyor are currently on jonwright repositories)
> continuous integration

- ImageD11/refinegrains.py
- scripts/plotgrainhist.py
Please fix the OMSLOP thing too then!
> program on #9 2D picture. noted OMSLOP not working here

- setup.py
CI still failing on sqlite3...
> fix dependency problem

- sandbox/peaksearch_nxs.py
- sandbox/peaksearcher_nxs.py
This is an altered peaksearcher.py script that reads files to search and omega motor position values from a Nexus file. Changed command line arguments accordingly.
> Peaksearch from NXS files

- ImageD11src/__init__.py
- ImageD11src/cImageD11.py
- ImageD11src/indexing.py
- ImageD11src/sparseframe.py
- ImageD11src/unitcell.py
- README.md
- setup.py
- src/bldlib.py
- test/eps_sig/test_eps.py
> Fix build for other platforms 

- setup.py
> try to fix for pip

- ImageD11src/tkGui/guitransformer.py
- ImageD11src/transformer.py
Hi: a quick change to ImageD11 gui: export 2theta histograms to text file for further analysis
> New feature: expert 2theta histogram to text file

- ImageD11src/tkGui/guitransformer.py
- ImageD11src/transform.py
- ImageD11src/transformer.py
I created a new function to compute twotheta histograms. Uses numpy and allow for weights. 
I would like, then, to add an option in transformer and the gui to choose whether to use number of peaks or peak intensity for calculating the histogram.
Would you be ok with this?
> Numpy based histograms + weighting feature

- .travis.yml
- pyproject.toml
- setup.py
It seems the pyproject.toml is somehow problematic with `pip install --user --editable`. Like this it seems to work, but needs testing to see if it still works for setting up an empty conda/venv.
> An attempt to fix pip install

- ImageD11/cImageD11_docstrings.py
- ImageD11/columnfile.py
- ImageD11/peaksearcher.py
- ImageD11/sinograms/dataset.py
- ImageD11/sinograms/lima_segmenter.py
- ImageD11/sinograms/properties.py
- ImageD11/sparseframe.py
- setup.py
- src/_cImageD11.pyf
- src/sparse_image.c
- test/test_localmaxlabel.py
Further tests and debugging will be needed, but we have seen >100 fps/core on typical ID11 s3DXRD frames.
> Calling bslz4_to_sparse external module

- ImageD11/columnfile.py
- ImageD11/sinograms/lima_segmenter.py
- ImageD11/transformer.py
1) use the bg image in ImageD11/columnfile.py
2) numpy deleted bools in ImageD11/sinograms/lima_segmenter.py
3) change numpy.float to float in ImageD11/transformer.py
> use the bg image, numpy deleted bools and numpy.float

- .github/workflows/build_flake_pytest_ubuntu2004.yml
- ImageD11/sinograms/assemble_label.py
- ImageD11/sinograms/roi_iradon.py
> Add dty shifts and roi for iradon

- ImageD11/sinograms/dataset.py
- ImageD11/sinograms/lima_segmenter.py
- ImageD11/sinograms/properties.py
- ImageD11/sinograms/properties.py.sav
- ImageD11/sinograms/roi_iradon.py
- ImageD11/sparseframe.py
- sandbox/matchquick.py
- setup.py
- test/testdatasets/test_datasets.py
Less memory usage by ImageD11/sinograms/properties.py
> Should work for bigger s3DXRD maps

- ImageD11/blobcorrector.py
added a new method to blobcorrector.correctorcalss to do image distorsion correction using a pixel LUT. Faster for large peakfiles
> pixel lut method fo Image distorsion correction 

- ImageD11/sinograms/lima_segmenter.py
... it was a lazy error in the original code assuming that most pixels are not masked. This means for limasegmenter "1" means masked, "0" means not masked and no other value is expected.
> This lets you use a mask covering most of the image

- ImageD11/cImageD11.py
- ImageD11/sinograms/lima_segmenter.py
- ImageD11/sinograms/point_by_point.py
- ImageD11/sparseframe.py
- ImageD11/sym_u.py
- test/test_forking.py
Yet another attempt to fix the multiprocessing/threading thing.
It should also clean up the lima_segmenter code to stop using globals via fork (this misses a testcase, so I guess it is now broken)
> repair the multiprocessing thing?

- ImageD11/sinograms/lima_segmenter.py
... so I think this was actually tested (once)
> lima_segmenter to use fork free multiprocessing

- ImageD11/blobcorrector.py
- ImageD11/columnfile.py
- ImageD11/sinograms/properties.py
- ImageD11/transform.py
- docs/sphx/ExampleNotebooks/sample_shape.ipynb
- src/_cImageD11.pyf
- src/cdiffraction.c
This computes a sample shape in an example notebook.
The rest of the patches are to get the first part of that running faster.
> Speed up and example notebook

- ImageD11/sinograms/geometry.py
@jadball OK? Again black has trashed the formatting. The first diff might be cleaner if there is a way to see it.
> Remove implied units (microns vs mm for dty vs diffty)

- ImageD11/columnfile.py
- src/cdiffraction.c
- test/test_columnfile.py
> Fix bug in columnfile.updateGeometry

- ImageD11/columnfile.py
> Bugfix PandasColumnfile

- ImageD11/columnfile.py
- test/test_columnfile.py
I have a feeling this is not quite right yet, but the testcase seems to pass.
> Attempt to repair attribute access fix #289

- ImageD11/sinograms/dataset.py
> Load via the init method because of the update paths bug

- ImageD11/columnfile.py
- ImageD11/sinograms/point_by_point.py
Issues seen for Tilman's example on the latest git master.
- icolf was not read in properly
- hkl max only needs to be for peaks used
- makerings in setpeaks should match the indexer ds_tol
> Fixes for latest pbp

- ImageD11/nbGui/S3DXRD/0_S3DXRD_segment_and_label.ipynb
- ImageD11/nbGui/segmenter_gui.py
- ImageD11/sinograms/lima_segmenter.py
Still needs the bootstrap to go into some other project?
> Compacted the 0_S3DXRD notebook

- ImageD11/nbGui/S3DXRD/0_segment_and_label.ipynb
Typo from testing snuck into the main notebooks, now removed
> Fix incorrect processed data path

- ImageD11/sinograms/dataset.py
> Fix typo in dataset.py

- ImageD11/__init__.py
https://github.com/FABLE-3DXRD/ImageD11/issues/371#issuecomment-2607164978
> Update version number to 2.0.5

- ImageD11/forward_model/forward_model.py
- ImageD11/forward_model/forward_projector.py
- ImageD11/forward_model/test_forward_projector_principle.ipynb
- ImageD11/forward_model/test_forward_projector_to_cf.ipynb
small fixes with 4D peak merging for forward_projector and other minor updates
> small fixes with peak merging for forward_projector

- ImageD11/peakselect.py
@loichuder 
In order to do the phase based peaks filtering and intensity based peak filtering, I created a filter_peaks_by_intensity in peakselect.py file in imageD11,
> created a logic for filter_peaks_by_phase  in peakselect.py file

- ImageD11/indexing.py
- ImageD11/sinograms/point_by_point.py
see [#411](https://github.com/FABLE-3DXRD/ImageD11/issues/411#issue-2872711066)
> Bugfix in `indexing.indexer.refine()` #411

- ImageD11/peakselect.py
- ImageD11/refinegrains.py
- remove peaks close to mask. Could also be done (better) in the peak integration, but that is harder to write.
- compute a polarization factor
Together these can be used to get promising looking intensities (future: show how to fit some structure like silicon as an example)
> Better peak intensities

- .github/workflows/build_flake_pytest_ubuntu2004.yml
- ImageD11/cImageD11_docstrings.py
- ImageD11/lattice_reduction.py
- ImageD11/rc_array.py
- pyproject.toml
- setup.py
- src/_cImageD11.pyf
- src/cdiffraction.c
- src/closest.c
- src/connectedpixels.c
- src/localmaxlabel.c
- src/make_pyf.py
- src/sparse_image.c
- src/splat.c
- test/test_misori.py
Try ubuntu 22.04 (kicking the can down the road)
fixes #415
> Fix CI and builds on numpy 2

- ImageD11/__init__.py
- ImageD11/nbGui/S3DXRD/friedel_pair_map.ipynb
- README.md
New notebook to locate peaks inside the sample from scanning data.
> Friedel pair position mapping

- ImageD11/forward_model/grainmaps.py
Thanks @jadball, fix a bug with symmetry operations for disorientation
> fix a bug with symmetry operations for disorientation
