FABLE-3DXRD/ImageD11

- README.md
- appveyor.yml
Use h5py version 2.10 for windows CI (binary wheels are available for 32bit platform).
> fix the appveyor CI for h5py 

- pyproject.toml
An attempt to make `ImageD11`  installable with `pip` in a clean environment, without any prerequisites.
On a windows 10 using conda (as below) this installs with `pip` and passes `pytest` without any pre-installed packages such as `numpy` or the like. To replicate:
conda create -n dev_ImageD11 python=3.8
conda activate dev_ImageD11 
git clone https://github.com/FABLE-3DXRD/ImageD11.git
cd ImageD11
pip install -e .
conda install pytest
pytest
> Add pyproject.toml to avoid pre-installs with pip

- pyproject.toml
So pip is installing the latest numpy to compile when you have an older incompatible version installed already. At least I think that is what happened. So we try to depend on oldest-supported-numpy instead, which does not exist on python2.
> Trying to fix pip install / numpy problem

- .github/workflows/release.yml
This PR adds a github actions "workflow" to automate the generation of wheels thanks to [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) and the upload to pypi thanks to [gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish).
This workflow is triggered when a release is published in github.
I already did the set-up to use [pypi's trusted publishers](https://docs.pypi.org/trusted-publishers/). As it is you have to publish a github release on a tag starting with `v` to trigger the workflow and click on a button approve the upload to pypi. This can be more automated (e.g., upload when a tag is pushed to the repo but it makes it more sensitive to errors).
It build the source distribution and wheels for Python 3.7 to 3.12 for:
- MacOS: `universal2`, i.e., …
> Add build wheels, tarball and deploy to pypi

- ImageD11/eps_sig_solver_NEW.py
Create a new solver to compute strain and stress from ImageD11 ubis
> Add new solver for strain and stress 

- ImageD11/sinograms/assemble_label.py
set rather than list randomly permuted the order of scans. Oups.
> Bugfix assemble_label.py

- ImageD11/nbGui/S3DXRD/0_S3DXRD_segment_and_label_single_dset.ipynb
- ImageD11/nbGui/S3DXRD/1_S3DXRD_index_z_slice.ipynb
- ImageD11/nbGui/S3DXRD/2_S3DXRD_sinograms_map.ipynb
Adds some example notebooks for simple scanning 3DXRD data analysis.
The general plan is as follows:
1. These notebooks become the authoritative starting point for S3DXRD processing going forward
2. Update the Confluence documentation to point to the notebooks on GitHub
3. Make suggested changes/improvements by @jonwright
4. Move any scary maths out of the notebooks and into ImageD11 itself
5. Continue documentation of a few functions/figures that are still undocumented/uncommented
6. Do the same thing for box scanning
> Add scanning 3DXRD example notebooks

- .github/workflows/build_flake_pytest_ubuntu2004.yml
- setup.py
Until Numba updates to Python 3.12
This should fix the CI for Python 3.x
> Exclude Python 3.12 in setup.py

- ImageD11/columnfile.py
In a 4D merged peak colfile, we can exceed the int32 max value in the `sum_intensity` column (see image attached).
This leads to a loss of precision when saving to HDF.
This is resolved by changing to 64-bit dtypes for these values.
> Change from 32-bit to 64-bit for int and float in HDF colfile

- ImageD11/sinograms/dataset.py
- ImageD11/sinograms/roi_iradon.py
Apologies for many lines of changes, my code editor auto-linted things.
The changes to `dataset.py` are outlined:
1. Added `update_paths()` method to `DataSet` class
This function determines `self.analysispath` and a set of paths to directories and files such as `self.pksfile` and `self.grainsfile`
This function is called during `self.__init__()` but also at the end of `self.load()` because the paths depend on `self.sample` and `self.dataset` which are not defined when the main `load()` function is called (because an empty `DataSet()` object is created and afterwards loaded from file).
2. Added a default h5 file path to the `self.save()` and `self.load()` methods.
If no h5 path is manually provided, `h5name` is set to `self.dsfile_default` which is calculated in `self.update_paths()`
At …
> dataset.py file structure enforcement and MLEM mask

- .github/workflows/release.yml
This PR:
- Updates `cibuildwheel` action to fix an issue on Windows (see https://github.com/pypa/cibuildwheel/releases/tag/v2.16.5)
- Updates `upload|download-artifacts` actions: This now allows to download the produced wheel/tarball from the action page (see https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
> Update release continuous integration

- ImageD11/sinograms/assemble_label.py
- ImageD11/sinograms/properties.py
Also a threshold image option for assemblelabel.
> No more forks for the peak properties.

- ImageD11/nbGui/S3DXRD/1_S3DXRD_index_z_slice_minor_phase.ipynb
- ImageD11/nbGui/S3DXRD/2_S3DXRD_sinograms_map_minor_phase.ipynb
- ImageD11/nbGui/S3DXRD/4_S3DXRD_plot_both_phases.ipynb
- ImageD11/tkGui/twodplot.py
- ImageD11/transform.py
- Fix problems with log scale buttons in ImageD11_gui caused by twodplot.py 
- Replace outdated `np.int` in ImageD11/transform.py that was causing errors in ImageD11_gui
- Minor phase scanning notebooks now use nb_utils
> ImageD11_gui fixes and some scanning notebooks updates

- ImageD11/blobcorrector.py
- ImageD11/grain.py
- ImageD11/nbGui/S3DXRD/run_mlem_recon.py
- ImageD11/nbGui/nb_utils.py
- ImageD11/sinograms/dataset.py
- ImageD11/sinograms/lima_segmenter.py
- ImageD11/sinograms/roi_iradon.py
- ImageD11/sinograms/sinogram.py
Apologies for the monster commit! Key highlights below:
- New GrainSinogram class to handle building sinograms from a `Grain` and `DataSet` object.
- HDF5 load/save methods for `Grain` class
- Many useful helper functions in `DataSet` class (e.g getting peaks tables for you)
- Some utility functions inside `iradon`
- Lima segmenter now uses mask and background files from the dataset object if none are manually provided
- Utility function for `blobcorrector.py` to correct a columnfile with a spline
All the diffs should be readable aside from `grain.py` which I accidentally linted (sorry!) - look at the bottom of the file for new stuff added.
> Moving many functions from nbgui into ImageD11

- ImageD11/sinograms/roi_iradon.py
Should fix #250, tested with a phantom but needs testing for real :)
> Correct MLEM padding bug

- test/test_orix.py
Sorry - Black format messed up the diff. Main changes:
- the color tests have a smaller tolerance (orientation was wrong for blue)
- added a check on the code path of 1 UB vs many UBs
> reduce atol/rtol on tests

- ImageD11/unitcell.py
Importing a .gve file into the indexer with `indexer.readgvfile` calls `unitcell.cellfromstring` to build a unitcell from the parameters at the top of the .gve file.
This means that, for .gve files with spacegroup-style symmetries, a `str` type symmetry is passed to the `unitcell.__init__` method.
For numeric (i.e spacegroup) symmetries, this means we don't properly detect that a spacegroup is being supplied.
This patch fixes the bug - if the symmetry is a string, it checks if the string is a digit, and converts to int if possible before continuing the init.
> Unitcell: Try to cast symmetry to int during init

- .github/workflows/release.yml
Following some recent troubleshooting by @kif with this, this PR proposes to increase the verbosity of the build.
It also removes the `--pre` installation flag which makes the tests of the generated source tarball fail because it run the tests with numpy v2.
BTW, if you want to support numpy v2, the wheels should be generated with numpy v2.
> Release workflow: Increase verbosity of cibuildwheel

- ImageD11/sinograms/sinogram.py
This adds hkle labels to the grain sinograms.
Also adds the option to create moment sinograms (thanks to a useful discussion with Peter Modregger). These are useful because we want a sinogram of peak position. But we can't have that for pixels where there is no peak. So we can always have a sinogram of (position x intensity)  and another sinogram of intensity. Then we will not have to divide by zero anywhere.
> hkl labels for grain sinogram, also moment sinograms

- .github/workflows/release.yml
This PR updates the release workflow to:
- use `macos-13` (11 is no longer available and 12 is deprecated)
- fix the installation of dependencies for the tests to pass
Here is a manual run of it: https://github.com/FABLE-3DXRD/ImageD11/actions/runs/11384434752
> Update release workflow to use macos-13

- ImageD11/sinograms/point_by_point.py
- ImageD11/sinograms/tensor_map.py
@jonwright can you please double-check the maths behind this? I believe I am correctly modifying the distance but it'd be good to double-check: the new function `get_local_gv` does this for the indexer.
> Use xl, yl, zl for origin of diffraction calculation in PBP indexer

- ImageD11/forward_model/__init__.py
- ImageD11/forward_model/forward_model.py
- ImageD11/forward_model/io.py
- ImageD11/forward_model/ori_converter.py
- ImageD11/forward_model/pars_conversion.py
- ImageD11/forward_model/sample_environment.py
- ImageD11/forward_model/schmidt_factor.py
The aim is to exploit forward model for the following purposes:
1) facilitate analysis for (s)3DXRD by filtering and cleaning peaks for indexed grains, calculating completeness
2) bridging the combined analysis between DCT and (s)3DXRD for the same sample but measured in different geometries/instruments
3) forward model based reconstruction for both near-field and far-field geometries
4) parameters conversion among ImageD11 par, DCT parameters, poni, which all can be converted to a dictionary and compatible with fwd-DCT parameters
5) other auxillary tools for multi-modality analysis, including interacting with PCT, sample environment, orientation conversion, deformation analysis (schmidt factor calc) etc.
A lot more is under development...
> add forward_model for facilitating (s)3DXRD analysis

- ImageD11/sinograms/tensor_map.py
Unlikely to have caused problems in current usage - regular notebook workflow doesn't initiate a refinement from a TensorMap with more than one z layer (z stacking comes later). In the previous code, `mi` was always 0, because `recon_index_to_map` (correctly) defaults to a 2D slice. We should be checking the `self.phase_ids` phase mask at the user-supplied `z_layer` value rather than 0.
> Fix bug with creating PBPMap from multi-layer TensorMap

- ImageD11/nbGui/segmenter_gui.py
> Extract chooseframe function from segmenter_gui

- ImageD11/peakselect.py
We split the sorted_peak_intensity_mask function into two function, one for plotting another one for computing the data.
Will be using the function that computes data in our EWoks Task
> plot and data separation on sorted_peak_intensity_mask

- ImageD11/frelon_peaksearch.py
> frelon_peaksearch: allow to pass `kwargs` to `process_map` in `process` function

- ImageD11/nbGui/segmenter_gui.py
- ImageD11/nbGui/segmenter_gui_utils.py
The import of functions from `segment_gui` raises a `ModuleNotFoundError: ipywidgets` with a regular install of ImageD11 (i.e. no `more` or `full` extra requirements)
These utils actually do not depend on `ipywidgets`: we should be able to expose them with a regular installation.
To solve this, I moved the utils to a separate file. I kept the compatiblity with the existing notebooks by reimporting the utils functions in `segmenter_gui` (so that, for example, `segmenter_gui.guess_ESRF_paths()` still works)
> Move SegmenterGui utils into a separate file

- ImageD11/forward_model/__init__.py
- ImageD11/forward_model/forward_model.py
- ImageD11/forward_model/forward_projector.py
- ImageD11/forward_model/grainmaps.py
- ImageD11/forward_model/io.py
- ImageD11/forward_model/ori_converter.py
- ImageD11/forward_model/pars_conversion.py
- ImageD11/forward_model/test_forward_model_matching_peaks.ipynb
- ImageD11/forward_model/test_forward_projector_principle.ipynb
- ImageD11/forward_model/test_forward_projector_to_cf.ipynb
- ImageD11/forward_model/test_grainmaps.ipynb
- ImageD11/forward_model/test_iterative_indexing.ipynb
- ImageD11/forward_model/test_pars_conversion.ipynb
The main changes are:
1) add forward_projector.py, take the experimentally reconstructed tensor map (from pbp_tensor_refined or tensor map in xx_grains.h5), define the beam profile and forward compute peaks and output them as cf_2d, cf_3d and cf_4d, which have the same formats as ImageD11 column file. The goal is to check the peaks difference and bridge with DCT, and hopefully helps to develop iterative forward and back projections;
2) add grainmaps.py, main features are i) merge regions when the voxels have similar orientations, 'similar' is defined by calculating the misorientation to the mean orientation of the region, therefore a min_misorientation is defined by the user to identify grain IDs (called 'labels'); ii) indexing_iterative for match peaks with already-indexed grains, then …
> add forward_projector, grainmaps and updates with forward_model etc to forward compute

- ImageD11/indexing.py
@jonwright, @jadball, @loichuder 
even if wavelength is present in kwds, Python evaluates float(colfile.parameters.get("wavelength")) before calling kwds.get().
This happens for some reason, and produces an error, so I had to rewrite the logic like this 
```
w = kwds.get("wavelength")
if w is None:
w = colfile.parameters.get("wavelength")
if w is None:
raise ValueError("Wavelength must be provided either in kwds or colfile.parameters")
```
> update on indexer_from_colfile_and_ucell function

- ImageD11/columnfile.py
- ImageD11/frelon_peaksearch.py
- ImageD11/nbGui/S3DXRD/0_segment_frelon.ipynb
- ImageD11/nbGui/S3DXRD/tomo_2_map.ipynb
- ImageD11/nbGui/S3DXRD/tomo_2_map_minor_phase.ipynb
- ImageD11/nbGui/TDXRD/0_segment_frelon.ipynb
- ImageD11/nbGui/segmenter_gui.py
- test/papermill_test_notebooks.py
Moderately hacky approach to segment multi-scan Frelon data, then perform a 4D merge, if you did S3DXRD with the Frelon. See `S3DXRD/0_segment_frelon.ipynb` for usage guidelines - basically just pass `scan_number=[0, 1, 2, 3]` or any iterable to trigger the 4D merging over `(dty, omega)` rather than the 3D merging over `omega`. We are due for a major refactor of segmentation and merging soon to conceptually separate them and give users more freedom of what to do...
> 4D segmentation for S3DXRD scans with Frelon

- ImageD11/grain.py
`grain.translation` can be `None`: https://github.com/FABLE-3DXRD/ImageD11/blob/0daa4f1e629a47de707aa7ce0344e1d09ae83cdc/ImageD11/grain.py#L55
> Fix error when saving grain with no translation

- ImageD11/forward_model/pars_conversion.py
update pars_conversion to account for the new version of parameters file in DCT
> update pars_conversion to account for the new version of parameters file in DCT

- ImageD11/frelon_peaksearch.py
It seems flat was overwriting dark rather than chaining the correction?
> Fix wrong frelon flat/dark correction

- ImageD11/sinograms/dataset.py
- ImageD11/sinograms/lima_segmenter.py
Please do not merge yet. 
ds.ostep is still wrong.
We have:
```
1.1 : fast_start_pos = -119.55, fast_step_size = 0.05, fast_npoints = 7220
2.1 : fast_start_pos =  263.15, fast_step_size = 0.05, fast_npoints = 7220
...
10.1 : fast_start_pos =  3324.75, fast_step_size = 0.05, fast_npoints = 7220
```
We could pick up ds.ostep from master -> scan/instrument/fscan_parameters. 
Or we could leave it as a manual fix for this kind of case.
Or we could fit the slope omega vs frame number slope (interlaced?) for each row of the sinogram.
> dataset.obincens

- ImageD11/forward_model/grainmaps.py
minor update with exporting xdmf (including 5 dimensional datasets, e.g. eps_sample, UBI etc) for grainmaps.py, very useful for stacked 3D s3DXRD volume.
> minor update with exporting xdmf (including 5 dimensional datasets, e.g. eps_sample, UBI etc) for grainmaps.py

- setup.py
This PR:
- fixes a compilation issue if there is 2 spaces in CFLAGS or LDFLAGS env. variables (occuring in new jupyter-slurm conda env). In this case an empty string is passed as an argument to the compiler as `""`.
- avoids the use of `self.extensions` and use `ext` instead since it is the currently handled Extension
- avoid use of `ext_package` and use the fully qualified name in the Extension: Without this, the `_cImageD11` is advertised as a "top level" module (I don't know why, it shouldn't). To check: `from importlib.metadata import packages_distributions; packages_distributions()['_cImageD11']`
> Fix setup.py with CFLAGS/LDFLAGS

- ImageD11/forward_model/ori_converter.py
Error : 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function norm at 0x14c0143dd760>) found for signature:
>>> norm(array(int64, 1d, C))
```
Reproduce example : 
```
r = np.array([0,0,0])
ori_converter.rod2quat(r)
```
> Fix a bug in rod2quat when r=[0,0,0], njit fails with np.linalg maybe ?

- ImageD11/frelon_peaksearch.py
Zombie code has awaken! :zombie: 
When iterating multiple scans for frelon segmentation with intensity normalisation active, there is a bug :bug:  in the indexation that causes a hard crash regradless of input. The typo has been fixed.
This implies that the template `0_segment_frelon.ipynb` is broken before this patch. With respet to this template, please also note that some of the defult frelon files (such as the dark) is not setup for user permission :see_no_evil: 
Cheers
Axel
> bugfix forfrelon segmenter when intensity normalization is active

- .github/workflows/release.yml
- pyproject.toml
- setup.py
This PR updates the release workflow to use `numpy` wheels for all platforms.
It also remove `six` from build dependencies since it is apparently not used for building the package.
closes #500
> Update release workflow

- ImageD11/forward_model/pars_conversion.py
New version of pyFAI, there is a 'shape' key when loading a poni file with `pyFAI.load('poni').getImageD11`. It creates an error when trying to convert from par to poni : `conv.build_poni_from_ImageD11par`
> Quickfix pars_conversion.py

- ImageD11/sinograms/dataset.py
Fix `import_motors_from_master` always choosing scan 0 - I believe this is a bug that doesn't normally come up, but does for some 2d scan types. Saw this with much older S3DXRD datasets
> Fix import_motors_from_master always choosing scan 0
